package com.cutter.plotterctl;

public class WebUI {
    public static final String MAIN_HTML = "<!DOCTYPE html><html><head>"
        + "<meta charset='utf-8'>"
        + "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        + "<title>PlotterCtl</title>"
        + "<style>"
        + "*{box-sizing:border-box;margin:0;padding:0}"
        + "body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;min-height:100vh}"
        + ".header{background:#16213e;padding:12px 20px;display:flex;align-items:center;justify-content:space-between}"
        + ".header h1{font-size:20px;color:#0ff}"
        + ".status{font-size:13px;padding:4px 12px;border-radius:12px;background:#333}"
        + ".status.ok{background:#0a3d0a;color:#4f4}"
        + ".status.err{background:#3d0a0a;color:#f44}"
        + ".main{display:flex;gap:16px;padding:16px;flex-wrap:wrap}"
        + ".panel{background:#16213e;border-radius:8px;padding:16px;flex:1;min-width:300px}"
        + ".panel h2{font-size:16px;color:#0af;margin-bottom:12px}"
        + ".drop-zone{border:2px dashed #555;border-radius:8px;padding:40px 20px;text-align:center;cursor:pointer;transition:.2s}"
        + ".drop-zone:hover,.drop-zone.drag{border-color:#0af;background:#0af1}"
        + ".drop-zone input{display:none}"
        + ".file-info{margin-top:10px;font-size:13px;color:#aaa}"
        + ".preview-box{background:#111;border-radius:6px;margin-top:10px;position:relative;overflow:hidden}"
        + ".preview-box svg{width:100%;height:350px;display:block}"
        + "label{display:block;margin-top:12px;font-size:13px;color:#aaa}"
        + "label span{color:#0ff;float:right}"
        + "input[type=range]{width:100%;margin-top:4px;accent-color:#0af}"
        + "select{width:100%;margin-top:4px;padding:8px;background:#0d1b2a;color:#e0e0e0;border:1px solid #333;border-radius:6px;font-size:14px}"
        + ".preset-row{display:flex;gap:10px;margin-top:8px}"
        + ".preset-row>div{flex:1}"
        + ".btn{display:block;width:100%;padding:14px;margin-top:16px;border:none;border-radius:8px;font-size:16px;font-weight:bold;cursor:pointer;transition:.2s}"
        + ".btn-cut{background:#d32f2f;color:#fff}"
        + ".btn-cut:hover{background:#e53935}"
        + ".btn-cut:disabled{background:#555;color:#888;cursor:not-allowed}"
        + ".btn-stop{background:#f57f17;color:#fff;margin-top:8px}"
        + ".progress-wrap{margin-top:14px;display:none}"
        + ".progress-bar{height:24px;background:#333;border-radius:12px;overflow:hidden}"
        + ".progress-fill{height:100%;background:linear-gradient(90deg,#0af,#0f6);transition:width .3s;width:0%}"
        + ".progress-text{text-align:center;font-size:13px;margin-top:4px;color:#aaa}"
        + ".log{margin-top:10px;background:#111;border-radius:6px;padding:10px;font-family:monospace;font-size:11px;color:#4f4;max-height:150px;overflow-y:auto;white-space:pre-wrap}"
        + ".legend{margin-top:8px;font-size:11px;color:#888;display:flex;gap:16px;flex-wrap:wrap}"
        + ".legend i{display:inline-block;width:12px;height:12px;border-radius:2px;vertical-align:middle;margin-right:4px}"
        + "@media(max-width:700px){.main{flex-direction:column}.preset-row{flex-direction:column}}"
        + "</style></head><body>"
        + "<div class='header'><h1>PlotterCtl</h1><div id='conn' class='status'>Checking...</div></div>"
        + "<div class='main'>"
        // Left panel - upload and preview
        + "<div class='panel'>"
        + "<h2>Upload HPGL File</h2>"
        + "<div class='drop-zone' id='dropZone' onclick=\"document.getElementById('fileIn').click()\">"
        + "<div>Drop .hpgl file here or click to browse</div>"
        + "<input type='file' id='fileIn' accept='.hpgl,.plt,.hp,.hpg' onchange='handleFile(this.files[0])'>"
        + "</div>"
        + "<div class='file-info' id='fileInfo'></div>"
        + "<div class='preview-box' id='previewBox' style='display:none'>"
        + "<svg id='svgPreview' viewBox='0 0 100 100' preserveAspectRatio='xMidYMid meet'></svg>"
        + "</div>"
        + "<div class='legend' id='legend' style='display:none'>"
        + "<span><i style='background:#335'></i>Paper</span>"
        + "<span><i style='background:#552'></i>Feed zone</span>"
        + "<span><i style='background:#0f0'></i>Cut path</span>"
        + "<span><i style='background:#f00'></i>Move path</span>"
        + "</div>"
        + "</div>"
        // Right panel - settings
        + "<div class='panel'>"
        + "<h2>Presets</h2>"
        + "<div class='preset-row'>"
        + "<div>"
        + "<label>Paper Size</label>"
        + "<select id='paperSize' onchange='applyPaperPreset()'>"
        + "<option value='2100,2970'>A4 (210 x 297 mm)</option>"
        + "<option value='2970,4200'>A3 (297 x 420 mm)</option>"
        + "<option value='2160,2790'>Letter (216 x 279 mm)</option>"
        + "<option value='2160,3560'>Legal (216 x 356 mm)</option>"
        + "<option value='2800,5000'>11\" Roll (280 x 500 mm)</option>"
        + "<option value='2800,10000'>11\" Roll (280 x 1000 mm)</option>"
        + "<option value='0,0'>Custom</option>"
        + "</select>"
        + "</div>"
        + "<div>"
        + "<label>Material</label>"
        + "<select id='material' onchange='applyMaterialPreset()'>"
        + "<option value='2,2'>Standard Paper</option>"
        + "<option value='3,3'>Cardstock</option>"
        + "<option value='3,4'>Vinyl (thin)</option>"
        + "<option value='2,5'>Vinyl (thick)</option>"
        + "<option value='4,3'>Sticker Paper</option>"
        + "<option value='1,1'>Tracing Paper</option>"
        + "<option value='5,6'>Faux Leather</option>"
        + "<option value='0,0'>Custom</option>"
        + "</select>"
        + "</div>"
        + "</div>"
        + "<h2 style='margin-top:16px'>Cut Settings</h2>"
        + "<label>Speed <span id='speedVal'>2</span></label>"
        + "<input type='range' id='speed' min='1' max='10' value='2' oninput=\"document.getElementById('speedVal').textContent=this.value\">"
        + "<label>Force / Pressure <span id='forceVal'>2</span></label>"
        + "<input type='range' id='force' min='1' max='10' value='2' oninput=\"document.getElementById('forceVal').textContent=this.value\">"
        + "<label>Paper Feed before cut (mm) <span id='feedVal'>200</span></label>"
        + "<input type='range' id='feed' min='0' max='500' value='200' step='10' oninput=\"document.getElementById('feedVal').textContent=this.value;updatePreview()\">"
        + "<button class='btn btn-cut' id='btnCut' onclick='startCut()' disabled>Start Cutting</button>"
        + "<button class='btn btn-stop' id='btnStop' onclick='stopCut()' style='display:none'>Stop</button>"
        + "<div class='progress-wrap' id='progressWrap'>"
        + "<div class='progress-bar'><div class='progress-fill' id='progressFill'></div></div>"
        + "<div class='progress-text' id='progressText'>0%</div>"
        + "</div>"
        + "<div class='log' id='log'>Ready.\n</div>"
        + "</div>"
        + "</div>"
        + "<script>"
        + "var polling=null,previewData=null;"
        // Paper presets: [width, height] in 0.1mm units
        + "var paperPresets={"
        + "'2100,2970':{w:2100,h:2970,name:'A4'},"
        + "'2970,4200':{w:2970,h:4200,name:'A3'},"
        + "'2160,2790':{w:2160,h:2790,name:'Letter'},"
        + "'2160,3560':{w:2160,h:3560,name:'Legal'},"
        + "'2800,5000':{w:2800,h:5000,name:'11\" Roll'},"
        + "'2800,10000':{w:2800,h:10000,name:'11\" Roll Long'}"
        + "};"
        + "function log(m){var l=document.getElementById('log');l.textContent+=m+'\\n';l.scrollTop=l.scrollHeight}"
        // Apply paper preset
        + "function applyPaperPreset(){updatePreview()}"
        // Apply material preset
        + "function applyMaterialPreset(){"
        + "var v=document.getElementById('material').value;"
        + "if(v==='0,0')return;"
        + "var p=v.split(',');"
        + "document.getElementById('speed').value=p[0];document.getElementById('speedVal').textContent=p[0];"
        + "document.getElementById('force').value=p[1];document.getElementById('forceVal').textContent=p[1];"
        + "log('Material preset: speed='+p[0]+' force='+p[1]);"
        + "}"
        // Get current paper size
        + "function getPaper(){"
        + "var v=document.getElementById('paperSize').value;"
        + "var p=paperPresets[v];"
        + "if(p)return p;"
        + "return null;"
        + "}"
        // Drag and drop
        + "var dz=document.getElementById('dropZone');"
        + "dz.addEventListener('dragover',function(e){e.preventDefault();dz.classList.add('drag')});"
        + "dz.addEventListener('dragleave',function(){dz.classList.remove('drag')});"
        + "dz.addEventListener('drop',function(e){e.preventDefault();dz.classList.remove('drag');if(e.dataTransfer.files.length)handleFile(e.dataTransfer.files[0])});"
        // File upload
        + "function handleFile(f){"
        + "if(!f)return;"
        + "log('Uploading '+f.name+'...');"
        + "var fd=new FormData();fd.append('file',f);"
        + "fetch('/api/upload',{method:'POST',body:fd}).then(r=>r.json()).then(d=>{"
        + "if(d.ok){"
        + "log('Uploaded: '+d.fileName+' ('+d.points+' points)');"
        + "document.getElementById('fileInfo').textContent=d.fileName+' - '+d.points+' points ('+Math.round(d.minX/10)+'x'+Math.round(d.minY/10)+' to '+Math.round(d.maxX/10)+'x'+Math.round(d.maxY/10)+' mm)';"
        + "if(d.speed>0){document.getElementById('speed').value=d.speed;document.getElementById('speedVal').textContent=d.speed}"
        + "if(d.force>0){document.getElementById('force').value=d.force;document.getElementById('forceVal').textContent=d.force}"
        + "document.getElementById('btnCut').disabled=false;"
        + "loadPreview()"
        + "}else{log('Error: '+d.error)}"
        + "}).catch(e=>log('Upload failed: '+e))}"
        // Load preview data from server then render
        + "function loadPreview(){"
        + "fetch('/api/preview').then(r=>r.json()).then(d=>{"
        + "previewData=d;updatePreview();"
        + "}).catch(e=>log('Preview error: '+e))}"
        // Render preview with paper overlay
        + "function updatePreview(){"
        + "if(!previewData)return;"
        + "var d=previewData;"
        + "var svg=document.getElementById('svgPreview');"
        + "var bx=document.getElementById('previewBox');"
        + "var lg=document.getElementById('legend');"
        + "bx.style.display='block';lg.style.display='flex';"
        + "var paper=getPaper();"
        + "var feedMm=parseInt(document.getElementById('feed').value)||0;"
        + "var feedU=feedMm*10;"
        // Calculate viewBox to fit both paper and design
        + "var vx=0,vy=0,vw,vh;"
        + "if(paper){"
        + "vw=paper.w;vh=paper.h;"
        // Expand viewbox if design goes outside paper
        + "var dw=d.maxX,dh=d.maxY+feedU;"
        + "if(dw>vw)vw=dw;if(dh>vh)vh=dh;"
        + "}else{"
        + "vw=(d.maxX-d.minX)||1;vh=(d.maxY-d.minY)||1;"
        + "vx=d.minX;vy=d.minY;"
        + "}"
        + "var pad=Math.max(vw,vh)*0.03;"
        + "svg.setAttribute('viewBox',(vx-pad)+' '+(vy-pad)+' '+(vw+pad*2)+' '+(vh+pad*2));"
        + "var html='';"
        // Draw paper background
        + "if(paper){"
        + "html+='<rect x=\"0\" y=\"0\" width=\"'+paper.w+'\" height=\"'+paper.h+'\" fill=\"#1a2540\" stroke=\"#335\" stroke-width=\"'+(vw/200)+'\" rx=\"'+(vw/100)+'\"/>';"
        // Feed zone (shaded area at top of paper that gets fed through)
        + "if(feedU>0){"
        + "html+='<rect x=\"0\" y=\"0\" width=\"'+paper.w+'\" height=\"'+Math.min(feedU,paper.h)+'\" fill=\"#2a2510\" opacity=\"0.5\"/>';"
        + "html+='<line x1=\"0\" y1=\"'+feedU+'\" x2=\"'+paper.w+'\" y2=\"'+feedU+'\" stroke=\"#664\" stroke-width=\"'+(vw/300)+'\" stroke-dasharray=\"'+(vw/50)+'\"/>';"
        + "html+='<text x=\"'+(paper.w/2)+'\" y=\"'+(feedU/2)+'\" text-anchor=\"middle\" fill=\"#886\" font-size=\"'+(vw/25)+'\">Feed: '+feedMm+'mm</text>';"
        + "}"
        // Paper dimensions label
        + "html+='<text x=\"'+(paper.w/2)+'\" y=\"'+(paper.h-pad)+'\" text-anchor=\"middle\" fill=\"#446\" font-size=\"'+(vw/30)+'\">'+paper.name+' ('+Math.round(paper.w/10)+' x '+Math.round(paper.h/10)+' mm)</text>';"
        + "}"
        // Draw design offset by feed distance
        + "var offY=feedU;"
        + "var sw=Math.max(vw,vh)/300;"
        // Draw move paths (pen up) as dashed red
        + "var prevX=0,prevY=0,firstPoint=true;"
        + "for(var i=0;i<d.points.length;i++){"
        + "var p=d.points[i];"
        + "var px=p[1],py=p[2]+offY;"
        + "if(p[0]===0&&!firstPoint){"
        + "html+='<line x1=\"'+prevX+'\" y1=\"'+prevY+'\" x2=\"'+px+'\" y2=\"'+py+'\" stroke=\"#600\" stroke-width=\"'+sw+'\" stroke-dasharray=\"'+(sw*3)+'\"/>';"
        + "}"
        + "prevX=px;prevY=py;firstPoint=false;}"
        // Draw cut paths (pen down) as solid green
        + "var path='';firstPoint=true;"
        + "for(var i=0;i<d.points.length;i++){"
        + "var p=d.points[i];"
        + "var px=p[1],py=p[2]+offY;"
        + "if(p[0]===0){"
        + "if(path)html+='<polyline points=\"'+path+'\" fill=\"none\" stroke=\"#0f0\" stroke-width=\"'+sw+'\"/>';"
        + "path=px+','+py;"
        + "}else{"
        + "if(!path)path=px+','+py;"
        + "else path+=' '+px+','+py;"
        + "}}"
        + "if(path)html+='<polyline points=\"'+path+'\" fill=\"none\" stroke=\"#0f0\" stroke-width=\"'+sw+'\"/>';"
        // Design bounding box
        + "if(d.points.length>0){"
        + "var bw=d.maxX-d.minX,bh=d.maxY-d.minY;"
        + "html+='<rect x=\"'+d.minX+'\" y=\"'+(d.minY+offY)+'\" width=\"'+bw+'\" height=\"'+bh+'\" fill=\"none\" stroke=\"#0af3\" stroke-width=\"'+sw+'\" stroke-dasharray=\"'+(sw*4)+'\"/>';"
        + "html+='<text x=\"'+(d.minX+bw/2)+'\" y=\"'+(d.minY+offY-pad/2)+'\" text-anchor=\"middle\" fill=\"#0af\" font-size=\"'+(Math.max(vw,vh)/35)+'\">Design: '+Math.round(bw/10)+' x '+Math.round(bh/10)+' mm</text>';"
        + "}"
        // Fit warning if design exceeds paper
        + "if(paper&&(d.maxX>paper.w||(d.maxY+offY)>paper.h)){"
        + "html+='<text x=\"'+(vw/2)+'\" y=\"'+(pad*3)+'\" text-anchor=\"middle\" fill=\"#f44\" font-size=\"'+(vw/20)+'\">Design exceeds paper!</text>';"
        + "}"
        + "svg.innerHTML=html;"
        + "}"
        // Start cut
        + "function startCut(){"
        + "var s=document.getElementById('speed').value;"
        + "var f=document.getElementById('force').value;"
        + "var fd=document.getElementById('feed').value;"
        + "log('Starting cut... speed='+s+' force='+f+' feed='+fd+'mm');"
        + "document.getElementById('btnCut').disabled=true;"
        + "document.getElementById('btnStop').style.display='block';"
        + "document.getElementById('progressWrap').style.display='block';"
        + "fetch('/api/cut',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({speed:parseInt(s),force:parseInt(f),feed:parseInt(fd)})})"
        + ".then(r=>r.json()).then(d=>{if(d.ok){log('Cut started');startPolling()}else{log('Error: '+d.error);document.getElementById('btnCut').disabled=false}})"
        + ".catch(e=>{log('Error: '+e);document.getElementById('btnCut').disabled=false})}"
        // Stop
        + "function stopCut(){"
        + "fetch('/api/stop',{method:'POST'}).then(r=>r.json()).then(d=>log(d.ok?'Stopped':'Error: '+d.error)).catch(e=>log('Error: '+e))}"
        // Poll status
        + "function startPolling(){"
        + "if(polling)clearInterval(polling);"
        + "polling=setInterval(function(){"
        + "fetch('/api/status').then(r=>r.json()).then(d=>{"
        + "document.getElementById('progressFill').style.width=d.progress+'%';"
        + "var stateText=d.state==='FEEDING'?'Feeding paper...':d.state==='CUTTING'?'Cutting '+d.progress+'% ('+d.sentChunks+'/'+d.totalChunks+')':d.state==='SENT'?'Plotter cutting... (data sent)':d.state;"
        + "document.getElementById('progressText').textContent=stateText;"
        + "if(d.state==='COMPLETE'||d.state==='ERROR'||d.state==='IDLE'){"
        + "clearInterval(polling);polling=null;"
        + "document.getElementById('btnCut').disabled=false;"
        + "document.getElementById('btnStop').style.display='none';"
        + "log(d.state==='COMPLETE'?'Cut complete!':'Cut ended: '+d.state+(d.error?' - '+d.error:''))}"
        + "}).catch(e=>{})},500)}"
        // Connection check
        + "function checkConn(){"
        + "fetch('/api/status').then(r=>r.json()).then(d=>{"
        + "var el=document.getElementById('conn');"
        + "el.textContent='Connected';el.className='status ok';"
        + "}).catch(e=>{var el=document.getElementById('conn');el.textContent='Disconnected';el.className='status err'})}"
        + "checkConn();setInterval(checkConn,5000);"
        + "</script></body></html>";
}
