package com.cutter.plotterctl;

public class WebUI {
    public static final String MAIN_HTML = "<!DOCTYPE html><html><head>"
        + "<meta charset='utf-8'>"
        + "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        + "<title>PlotterCtl</title>"
        + "<style>"
        + "*{box-sizing:border-box;margin:0;padding:0}"
        + "body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;min-height:100vh}"
        + ".header{background:#16213e;padding:12px 20px;display:flex;align-items:center;justify-content:space-between}"
        + ".header h1{font-size:20px;color:#0ff}"
        + ".status{font-size:13px;padding:4px 12px;border-radius:12px;background:#333}"
        + ".status.ok{background:#0a3d0a;color:#4f4}"
        + ".status.err{background:#3d0a0a;color:#f44}"
        + ".main{display:flex;gap:16px;padding:16px;flex-wrap:wrap}"
        + ".panel{background:#16213e;border-radius:8px;padding:16px;flex:1;min-width:300px}"
        + ".panel h2{font-size:16px;color:#0af;margin-bottom:12px}"
        + ".drop-zone{border:2px dashed #555;border-radius:8px;padding:40px 20px;text-align:center;cursor:pointer;transition:.2s}"
        + ".drop-zone:hover,.drop-zone.drag{border-color:#0af;background:#0af1}"
        + ".drop-zone input{display:none}"
        + ".file-info{margin-top:10px;font-size:13px;color:#aaa}"
        + ".preview-box{background:#111;border-radius:6px;margin-top:10px;position:relative;overflow:hidden}"
        + ".preview-box svg{width:100%;height:300px;display:block}"
        + "label{display:block;margin-top:12px;font-size:13px;color:#aaa}"
        + "label span{color:#0ff;float:right}"
        + "input[type=range]{width:100%;margin-top:4px;accent-color:#0af}"
        + ".btn{display:block;width:100%;padding:14px;margin-top:16px;border:none;border-radius:8px;font-size:16px;font-weight:bold;cursor:pointer;transition:.2s}"
        + ".btn-cut{background:#d32f2f;color:#fff}"
        + ".btn-cut:hover{background:#e53935}"
        + ".btn-cut:disabled{background:#555;color:#888;cursor:not-allowed}"
        + ".btn-stop{background:#f57f17;color:#fff;margin-top:8px}"
        + ".progress-wrap{margin-top:14px;display:none}"
        + ".progress-bar{height:24px;background:#333;border-radius:12px;overflow:hidden}"
        + ".progress-fill{height:100%;background:linear-gradient(90deg,#0af,#0f6);transition:width .3s;width:0%}"
        + ".progress-text{text-align:center;font-size:13px;margin-top:4px;color:#aaa}"
        + ".log{margin-top:10px;background:#111;border-radius:6px;padding:10px;font-family:monospace;font-size:11px;color:#4f4;max-height:150px;overflow-y:auto;white-space:pre-wrap}"
        + "@media(max-width:700px){.main{flex-direction:column}}"
        + "</style></head><body>"
        + "<div class='header'><h1>PlotterCtl</h1><div id='conn' class='status'>Checking...</div></div>"
        + "<div class='main'>"
        // Left panel
        + "<div class='panel'>"
        + "<h2>Upload HPGL File</h2>"
        + "<div class='drop-zone' id='dropZone' onclick=\"document.getElementById('fileIn').click()\">"
        + "<div>Drop .hpgl file here or click to browse</div>"
        + "<input type='file' id='fileIn' accept='.hpgl,.plt,.hp,.hpg' onchange='handleFile(this.files[0])'>"
        + "</div>"
        + "<div class='file-info' id='fileInfo'></div>"
        + "<div class='preview-box' id='previewBox' style='display:none'>"
        + "<svg id='svgPreview' viewBox='0 0 100 100' preserveAspectRatio='xMidYMid meet'></svg>"
        + "</div>"
        + "</div>"
        // Right panel
        + "<div class='panel'>"
        + "<h2>Cut Settings</h2>"
        + "<label>Speed <span id='speedVal'>2</span></label>"
        + "<input type='range' id='speed' min='1' max='10' value='2' oninput=\"document.getElementById('speedVal').textContent=this.value\">"
        + "<label>Force / Pressure <span id='forceVal'>2</span></label>"
        + "<input type='range' id='force' min='1' max='10' value='2' oninput=\"document.getElementById('forceVal').textContent=this.value\">"
        + "<label>Paper Feed before cut (mm) <span id='feedVal'>200</span></label>"
        + "<input type='range' id='feed' min='0' max='500' value='200' step='10' oninput=\"document.getElementById('feedVal').textContent=this.value\">"
        + "<button class='btn btn-cut' id='btnCut' onclick='startCut()' disabled>Start Cutting</button>"
        + "<button class='btn btn-stop' id='btnStop' onclick='stopCut()' style='display:none'>Stop</button>"
        + "<div class='progress-wrap' id='progressWrap'>"
        + "<div class='progress-bar'><div class='progress-fill' id='progressFill'></div></div>"
        + "<div class='progress-text' id='progressText'>0%</div>"
        + "</div>"
        + "<div class='log' id='log'>Ready.\n</div>"
        + "</div>"
        + "</div>"
        + "<script>"
        + "var polling=null;"
        + "function log(m){var l=document.getElementById('log');l.textContent+=m+'\\n';l.scrollTop=l.scrollHeight}"
        // Drag and drop
        + "var dz=document.getElementById('dropZone');"
        + "dz.addEventListener('dragover',function(e){e.preventDefault();dz.classList.add('drag')});"
        + "dz.addEventListener('dragleave',function(){dz.classList.remove('drag')});"
        + "dz.addEventListener('drop',function(e){e.preventDefault();dz.classList.remove('drag');if(e.dataTransfer.files.length)handleFile(e.dataTransfer.files[0])});"
        // File upload
        + "function handleFile(f){"
        + "if(!f)return;"
        + "log('Uploading '+f.name+'...');"
        + "var fd=new FormData();fd.append('file',f);"
        + "fetch('/api/upload',{method:'POST',body:fd}).then(r=>r.json()).then(d=>{"
        + "if(d.ok){log('Uploaded: '+d.fileName+' ('+d.points+' points)');document.getElementById('fileInfo').textContent=d.fileName+' - '+d.points+' points, bounds: '+d.minX+','+d.minY+' to '+d.maxX+','+d.maxY;"
        + "if(d.speed>0)document.getElementById('speed').value=d.speed,document.getElementById('speedVal').textContent=d.speed;"
        + "if(d.force>0)document.getElementById('force').value=d.force,document.getElementById('forceVal').textContent=d.force;"
        + "document.getElementById('btnCut').disabled=false;loadPreview()}"
        + "else{log('Error: '+d.error)}"
        + "}).catch(e=>log('Upload failed: '+e))}"
        // Preview
        + "function loadPreview(){"
        + "fetch('/api/preview').then(r=>r.json()).then(d=>{"
        + "var svg=document.getElementById('svgPreview');"
        + "var bx=document.getElementById('previewBox');"
        + "bx.style.display='block';"
        + "var pad=20,w=d.maxX-d.minX||1,h=d.maxY-d.minY||1;"
        + "svg.setAttribute('viewBox',(d.minX-pad)+' '+(d.minY-pad)+' '+(w+pad*2)+' '+(h+pad*2));"
        + "var html='<rect x=\"'+(d.minX-pad)+'\" y=\"'+(d.minY-pad)+'\" width=\"'+(w+pad*2)+'\" height=\"'+(h+pad*2)+'\" fill=\"#111\" />';"
        + "var path='';var drawing=false;"
        + "for(var i=0;i<d.points.length;i++){"
        + "var p=d.points[i];"
        + "if(p[0]===0){if(path){html+='<polyline points=\"'+path+'\" fill=\"none\" stroke=\"#0f0\" stroke-width=\"'+(w/300)+'\"/>';path=''}path=p[1]+','+p[2]}"
        + "else{if(!path)path=p[1]+','+p[2];else path+=' '+p[1]+','+p[2]}}"
        + "if(path)html+='<polyline points=\"'+path+'\" fill=\"none\" stroke=\"#0f0\" stroke-width=\"'+(w/300)+'\"/>';"
        + "svg.innerHTML=html;"
        + "}).catch(e=>log('Preview error: '+e))}"
        // Start cut
        + "function startCut(){"
        + "var s=document.getElementById('speed').value;"
        + "var f=document.getElementById('force').value;"
        + "var fd=document.getElementById('feed').value;"
        + "log('Starting cut... speed='+s+' force='+f+' feed='+fd+'mm');"
        + "document.getElementById('btnCut').disabled=true;"
        + "document.getElementById('btnStop').style.display='block';"
        + "document.getElementById('progressWrap').style.display='block';"
        + "fetch('/api/cut',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({speed:parseInt(s),force:parseInt(f),feed:parseInt(fd)})})"
        + ".then(r=>r.json()).then(d=>{if(d.ok){log('Cut started');startPolling()}else{log('Error: '+d.error);document.getElementById('btnCut').disabled=false}})"
        + ".catch(e=>{log('Error: '+e);document.getElementById('btnCut').disabled=false})}"
        // Stop
        + "function stopCut(){"
        + "fetch('/api/stop',{method:'POST'}).then(r=>r.json()).then(d=>log(d.ok?'Stopped':'Error: '+d.error)).catch(e=>log('Error: '+e))}"
        // Poll status
        + "function startPolling(){"
        + "if(polling)clearInterval(polling);"
        + "polling=setInterval(function(){"
        + "fetch('/api/status').then(r=>r.json()).then(d=>{"
        + "document.getElementById('progressFill').style.width=d.progress+'%';"
        + "var stateText=d.state==='FEEDING'?'Feeding paper...':d.state==='CUTTING'?'Cutting '+d.progress+'% ('+d.sentChunks+'/'+d.totalChunks+')':d.state==='SENT'?'Plotter cutting... (data sent)':d.state;"
        + "document.getElementById('progressText').textContent=stateText;"
        + "if(d.state==='COMPLETE'||d.state==='ERROR'||d.state==='IDLE'){"
        + "clearInterval(polling);polling=null;"
        + "document.getElementById('btnCut').disabled=false;"
        + "document.getElementById('btnStop').style.display='none';"
        + "log(d.state==='COMPLETE'?'Cut complete!':'Cut ended: '+d.state+(d.error?' - '+d.error:''))}"
        + "}).catch(e=>{})},500)}"
        // Connection check
        + "function checkConn(){"
        + "fetch('/api/status').then(r=>r.json()).then(d=>{"
        + "var el=document.getElementById('conn');"
        + "el.textContent='Connected';el.className='status ok';"
        + "}).catch(e=>{var el=document.getElementById('conn');el.textContent='Disconnected';el.className='status err'})}"
        + "checkConn();setInterval(checkConn,5000);"
        + "</script></body></html>";
}
